### ISSUE TITLE
Can This Script Run On WG2?

### ISSUE THREAD

**Issue by dongxuanlb** [scanlime/fygimbal#2]
When I try this script on WG2, it said timeout. something like below:

![snip20180520_1](https://user-images.githubusercontent.com/865803/40277581-c08e6c50-5c53-11e8-96d2-d1825a1d03aa.png)

**Comment by scanlime** [comment]
1. This is a different gimbal, I have no idea if it's compatible
2. the timeout could mean a lot of different things... how have you connected the gimbal? is it in the right mode? etc.

This really isn't something I've tried or can help with, you're on your own here.
